package ipdb

import "strings"

// cityByProvinceLatin 把拉丁字母的城市名翻译成中文，**按省分组**。
//
// 键是 (省, 拉丁城市名) 而不是单独的城市名，因为汉语拼音丢掉了声调与字形，
// 真实撞名不止一例：
//
//	Fuzhou  在福建省是福州市，在江西省是抚州市
//	Taizhou 在浙江省是台州市，在江苏省是泰州市
//
// 用单键表会让其中一个静默变成另一个，而规则表、界面、生成的配置全都渲染得
// 完全正常，只是城市是错的。
//
// 表是生成的，判据是**拼音翻译**而不是统计共现：对每个拉丁名，在 ip2region
// 同省的中文城市里找读音最接近的那个（多音字取全部读音，如「漯河」）。
// 一度用过「统计上与哪个中文名共现最多」，那是错的——它学到的是两个源的分歧
// 而不是译名：IP2Location 把吉林省一批段标为 Jilin，ip2region 说那些段在长春，
// 于是 Jilin 被翻译成了「长春市」。
//
// 采纳判据是「最高分 ≥ 0.65 且领先第二名 ≥ 0.12」，两条都不能少：
//
//   - 只看最高分，短串会撞上巧合匹配（Gaotang→枣庄市、Rencheng→聊城市）；
//   - 把门槛提到 0.7 挡巧合，又会误杀少数民族语与历史转写——它们本来就不是
//     汉语拼音（Hohhot/呼和浩特 0.67、Ordos/鄂尔多斯 0.62、Harbin/哈尔滨 0.92）。
//
// 当前表覆盖两个源中国段约六成的行。剩下四成是区级与街道级地名（Jinrongjie、
// Haidian、Songjiang 这类），它们的上级市无法从字面推出，一律留空——留空是
// 安全的，sameLocation 对「某一级一方为空」本来就视为相同；原样存入则会让
// 「存疑」标记对几乎每个 IP 亮起，那正是 city_name.go 记的那个已经修过的坑。
var cityByProvinceLatin = map[string]map[string]string{
	"上海市": {
		"Shanghai": "上海市",
	},
	"云南省": {
		"Baoshan":      "保山市",
		"Chuxiong":     "楚雄",
		"Dali":         "大理",
		"Haidong Zhen": "红河",
		"Honghe":       "红河",
		"Kunming":      "昆明市",
		"Kunyang":      "昆明市",
		"Lijiang":      "丽江市",
		"Lincang":      "临沧市",
		"Liujia":       "丽江市",
		"Menghuan":     "文山",
		"Pu'er":        "普洱市",
		"Qujing":       "曲靖市",
		"Wenlan":       "文山",
		"Wenshan":      "文山",
		"Yuxi":         "玉溪市",
		"Zhaotong":     "昭通市",
	},
	"内蒙古": {
		"Baotou":    "包头市",
		"Bayan Nur": "巴彦淖尔市",
		"Bayanhot":  "巴彦淖尔市",
		"Bayannur":  "巴彦淖尔市",
		"Chifeng":   "赤峰市",
		"Hohhot":    "呼和浩特市",
		"Hulunbuir": "呼伦贝尔市",
		"Tongliao":  "通辽市",
		"Ulanqab":   "乌兰察布市",
		"Wuhai":     "乌海市",
		"Xilinhot":  "锡林郭勒盟",
	},
	"台湾省": {
		"Dingdongshi": "屏东县",
		"Hualien":     "花莲县",
		"Huatan":      "花莲县",
		"Jincheng":    "金门县",
		"Jiufen":      "金门县",
		"Linnei":      "新北市",
		"Miaoli":      "苗栗县",
		"New Taipei":  "台北市",
		"Pingtung":    "屏东县",
		"Sanzhong":    "台中市",
		"Tainan":      "台南市",
		"Taipei":      "台北市",
		"Taoyuan":     "桃园市",
		"Tianzhong":   "台中市",
		"Ximen":       "金门县",
		"Xinli":       "新北市",
		"Yilan":       "宜兰县",
		"Yuanlin":     "云林县",
	},
	"吉林省": {
		"Baicheng":  "白城市",
		"Baishan":   "白山市",
		"Changchun": "长春市",
		"Hunchun":   "长春市",
		"Jilin":     "吉林市",
		"Kuancheng": "白城市",
		"Liaoyuan":  "辽源市",
		"Lüyuan":    "辽源市",
		"Siping":    "四平市",
		"Songyuan":  "松原市",
		"Tonghua":   "通化市",
		"Yanji":     "延边",
	},
	"四川省": {
		"Bazhong":   "巴中市",
		"Chengdu":   "成都市",
		"Dazhou":    "达州市",
		"Deyang":    "德阳市",
		"Emeishan":  "眉山市",
		"Guang'an":  "广安市",
		"Guangyuan": "广元市",
		"Guang’an":  "广安市",
		"Hejiang":   "内江市",
		"Leshan":    "乐山市",
		"Liucheng":  "成都市",
		"Luocheng":  "成都市",
		"Luzhou":    "泸州市",
		"Meishan":   "眉山市",
		"Mianyang":  "绵阳市",
		"Nanchong":  "南充市",
		"Neijiang":  "内江市",
		"Panzhihua": "攀枝花市",
		"Pitong":    "自贡市",
		"Suining":   "遂宁市",
		"Yibin":     "宜宾市",
		"Zigong":    "自贡市",
		"Ziyang":    "资阳市",
	},
	"天津市": {
		"Tianjin": "天津市",
	},
	"宁夏": {
		"Guyuan":     "固原市",
		"Shizuishan": "石嘴山市",
		"Wuzhong":    "吴忠市",
		"Yinchuan":   "银川市",
		"Zhongwei":   "中卫市",
	},
	"安徽省": {
		"Anqing":           "安庆市",
		"Bengbu":           "蚌埠市",
		"Bozhou":           "亳州市",
		"Chizhou":          "池州市",
		"Chuzhou":          "滁州市",
		"Cihu":             "池州市",
		"Dangcheng":        "宣城市",
		"Dingcheng":        "宣城市",
		"Fuyang":           "阜阳市",
		"Gushu":            "芜湖市",
		"Hefei":            "合肥市",
		"Huaibei":          "淮北市",
		"Huainan":          "淮南市",
		"Huangshan":        "黄山市",
		"Huicheng":         "宣城市",
		"Lu'an":            "六安市",
		"Ma'anshan":        "马鞍山市",
		"Ma’anshan":        "马鞍山市",
		"Sanjiang":         "安庆市",
		"Suzhou":           "宿州市",
		"Tongling":         "铜陵市",
		"Tonglingshihuihe": "铜陵市",
		"Wuhu":             "芜湖市",
		"Xuancheng":        "宣城市",
		"Yanghu":           "阜阳市",
	},
	"山东省": {
		"Beizhai":   "威海市",
		"Binzhou":   "滨州市",
		"Decheng":   "聊城市",
		"Dengzhou":  "德州市",
		"Dezhou":    "德州市",
		"Dongying":  "东营市",
		"Feicheng":  "聊城市",
		"Heze":      "菏泽市",
		"Jinan":     "济南市",
		"Jining":    "济宁市",
		"Juancheng": "聊城市",
		"Liaocheng": "聊城市",
		"Qingdao":   "青岛市",
		"Qingzhou":  "滨州市",
		"Rizhao":    "日照市",
		"Tai'an":    "泰安市",
		"Tai’an":    "泰安市",
		"Tancheng":  "聊城市",
		"Taozhuang": "枣庄市",
		"Tianfu":    "泰安市",
		"Weifang":   "潍坊市",
		"Weihai":    "威海市",
		"Xintai":    "烟台市",
		"Yanta":     "烟台市",
		"Yantai":    "烟台市",
		"Yishui":    "烟台市",
		"Yucheng":   "聊城市",
		"Zaozhuang": "枣庄市",
		"Zhu Cheng": "聊城市",
		"Zhucheng":  "聊城市",
		"Zibo":      "淄博市",
	},
	"山西省": {
		"Changning":  "长治市",
		"Changzhi":   "长治市",
		"Datong":     "大同市",
		"Huozhou":    "朔州市",
		"Jincheng":   "晋城市",
		"Jinzhong":   "晋中市",
		"Linfen":     "临汾市",
		"Liuxiang":   "吕梁市",
		"Lüliang":    "吕梁市",
		"Shuozhou":   "朔州市",
		"Taiyuan":    "太原市",
		"Taiyuanshi": "太原市",
		"Xinzhou":    "忻州市",
		"Yangquan":   "阳泉市",
		"Yuncheng":   "运城市",
	},
	"广东省": {
		"Chaozhou":      "潮州市",
		"Chengdong":     "湛江市",
		"Chiwan":        "湛江市",
		"Dalang":        "湛江市",
		"Daojiao":       "湛江市",
		"Dongguan":      "东莞市",
		"Donghuan":      "东莞市",
		"Dongqu":        "东莞市",
		"Foshan":        "佛山市",
		"Fusha":         "佛山市",
		"Gangkou":       "广州市",
		"Gongguan":      "东莞市",
		"Guangzhou":     "广州市",
		"Heyuan":        "河源市",
		"Hongshan":      "中山市",
		"Houhai":        "珠海市",
		"Huanggang":     "阳江市",
		"Huizhou":       "惠州市",
		"Jiangmen":      "江门市",
		"Jieyang":       "揭阳市",
		"Langtian":      "阳江市",
		"Leizhou":       "梅州市",
		"Maoming":       "茂名市",
		"Mayong":        "茂名市",
		"Meizhou":       "梅州市",
		"Mingjing":      "阳江市",
		"Minzhu":        "梅州市",
		"Nanlang":       "湛江市",
		"Nantou":        "汕头市",
		"Qiaonan":       "清远市",
		"Qingyuan":      "清远市",
		"Sanbu":         "汕头市",
		"Sanweicun":     "汕尾市",
		"Shantou":       "汕头市",
		"Shanwei":       "汕尾市",
		"Shaoguan":      "韶关市",
		"Shatou":        "汕头市",
		"Shawei":        "汕尾市",
		"Shunde":        "汕尾市",
		"Songgang":      "东莞市",
		"Tangjiawan":    "阳江市",
		"Tanglang":      "阳江市",
		"Tieyong":       "揭阳市",
		"Xiegang":       "揭阳市",
		"Xingtan":       "清远市",
		"Yangjiang":     "阳江市",
		"Yangjiao":      "阳江市",
		"Yuanzhou":      "广州市",
		"Yunfu":         "云浮市",
		"Zhangmutou":    "汕头市",
		"Zhanjiang":     "湛江市",
		"Zhaoqing":      "肇庆市",
		"Zhongshan":     "中山市",
		"Zhongshangang": "中山市",
		"Zhuhai":        "珠海市",
	},
	"广西": {
		"Baise":         "百色市",
		"Beihai":        "北海市",
		"Chongzuo":      "崇左市",
		"Fangchenggang": "防城港市",
		"Guigang":       "贵港市",
		"Guilin":        "桂林市",
		"Hechi":         "河池市",
		"Hengzhou":      "贺州市",
		"Hezhou":        "贺州市",
		"Laibin":        "来宾市",
		"Liangqing":     "南宁市",
		"Liuchow":       "柳州市",
		"Liuzhou":       "柳州市",
		"Nandan":        "南宁市",
		"Nanning":       "南宁市",
		"Qinzhou":       "钦州市",
		"Qisha":         "百色市",
		"Wuzhi":         "梧州市",
		"Wuzhou":        "梧州市",
		"Xingning":      "南宁市",
		"Yongning":      "南宁市",
		"Yulin":         "玉林市",
	},
	"新疆": {
		"Aksu":    "阿克苏地区",
		"Altay":   "阿勒泰地区",
		"Changji": "昌吉",
		"Hami":    "哈密市",
		"Hotan":   "和田地区",
		"Huiyuan": "和田地区",
		"Karamay": "克拉玛依市",
		"Kashgar": "喀什地区",
		"Tacheng": "塔城地区",
		"Turpan":  "吐鲁番市",
	},
	"江苏省": {
		"Bacheng":     "盐城市",
		"Changshu":    "常州市",
		"Changzhou":   "常州市",
		"Fengcheng":   "盐城市",
		"Hai’an":      "淮安市",
		"Huai'an":     "淮安市",
		"Huaqiao":     "淮安市",
		"Huashi":      "淮安市",
		"Huayang":     "淮安市",
		"Hutang":      "淮安市",
		"Jiangwang":   "连云港市",
		"Jingjiang":   "镇江市",
		"Lianyun":     "连云港市",
		"Lianyungang": "连云港市",
		"Lidian":      "宿迁市",
		"Nanjing":     "南京市",
		"Nantong":     "南通市",
		"Pancheng":    "盐城市",
		"Qinnan":      "宿迁市",
		"Qixia":       "宿迁市",
		"Suqian":      "宿迁市",
		"Suzhou":      "苏州市",
		"Taihu":       "泰州市",
		"Taizhou":     "泰州市",
		"Wuxi":        "无锡市",
		"Xilin":       "宿迁市",
		"Xuzhou":      "徐州市",
		"Yancheng":    "盐城市",
		"Yangzhou":    "扬州市",
		"Yuanhe":      "盐城市",
		"Yuanzhu":     "扬州市",
		"Yuexi":       "无锡市",
		"Yugang":      "连云港市",
		"Zhenjiang":   "镇江市",
		"Zhetang":     "镇江市",
	},
	"江西省": {
		"Fuzhou":      "抚州市",
		"Ganzhou":     "赣州市",
		"Ji'an":       "吉安市",
		"Jingdezhen":  "景德镇市",
		"Jiujiang":    "九江市",
		"Ji’an":       "吉安市",
		"Nanchang":    "南昌市",
		"Nanchangshi": "南昌市",
		"Nan’an":      "南昌市",
		"Pingxiang":   "萍乡市",
		"Shangrao":    "上饶市",
		"Xinyu":       "新余市",
		"Yangzizhou":  "赣州市",
		"Yichun":      "宜春市",
		"Yingtan":     "鹰潭市",
	},
	"河北省": {
		"Baixiang":     "保定市",
		"Baoding":      "保定市",
		"Bazhou":       "沧州市",
		"Bencheng":     "承德市",
		"Cangzhou":     "沧州市",
		"Chengde":      "承德市",
		"Dingzhou":     "沧州市",
		"Hengshui":     "衡水市",
		"Langfang":     "廊坊市",
		"Pingshu":      "衡水市",
		"Qinhuangdao":  "秦皇岛市",
		"Rencheng":     "承德市",
		"Shijiazhuang": "石家庄市",
		"Tangshan":     "唐山市",
		"Xingtai":      "邢台市",
		"Xinji":        "邢台市",
		"Zhangjiakou":  "张家口市",
	},
	"河南省": {
		"Hebi":         "鹤壁市",
		"Hongqi":       "商丘市",
		"Jianxi":       "济源市",
		"Jiaozuo":      "焦作市",
		"Jiyuan":       "济源市",
		"Kaifeng":      "开封市",
		"Laohe":        "漯河市",
		"Luoyang":      "洛阳市",
		"Mucheng":      "许昌市",
		"Pingdingshan": "平顶山市",
		"Puyang":       "濮阳市",
		"Sanmenxia":    "三门峡市",
		"Shangqiu":     "商丘市",
		"Shenjian":     "信阳市",
		"Xingyang":     "信阳市",
		"Xinxiang":     "新乡市",
		"Xinyang":      "信阳市",
		"Xinye":        "信阳市",
		"Xuchang":      "许昌市",
		"Zhengzhou":    "郑州市",
		"Zhongmou":     "周口市",
		"Zhoukou":      "周口市",
		"Zhumadian":    "驻马店市",
	},
	"浙江省": {
		"Hangzhou":    "杭州市",
		"Huzhou":      "湖州市",
		"Jiangcun":    "嘉兴市",
		"Jianhu":      "金华市",
		"Jiaxing":     "嘉兴市",
		"Jiefang":     "嘉兴市",
		"Jinhua":      "金华市",
		"Jiubao":      "金华市",
		"Lishui":      "丽水市",
		"Ningbo":      "宁波市",
		"Qushan":      "舟山市",
		"Quzhou":      "衢州市",
		"Shanhu":      "杭州市",
		"Shankou":     "杭州市",
		"Shaoxing":    "绍兴市",
		"Sijiqing":    "嘉兴市",
		"Taizhou":     "台州市",
		"Wenzhou":     "温州市",
		"Xiangzhu":    "杭州市",
		"Xiaying":     "嘉兴市",
		"Xixing":      "嘉兴市",
		"Yunhe":       "温州市",
		"Zhaobaoshan": "舟山市",
		"Zhoushan":    "舟山市",
		"Zhuji":       "宁波市",
	},
	"海南省": {
		"Danzhou":  "儋州市",
		"Dazhipo":  "儋州市",
		"Haikou":   "海口市",
		"Sanya":    "三亚市",
		"Yingzhou": "儋州市",
	},
	"湖北省": {
		"Enshi":     "恩施",
		"Ezhou":     "鄂州市",
		"Guangshui": "黄石市",
		"Guizhou":   "随州市",
		"Huanggang": "黄冈市",
		"Huangmei":  "黄石市",
		"Huangshi":  "黄石市",
		"Jingmen":   "荆门市",
		"Jingzhou":  "荆州市",
		"Lichuan":   "宜昌市",
		"Nanhu":     "咸宁市",
		"Qianjiang": "咸宁市",
		"Shiyan":    "十堰市",
		"Shizishan": "十堰市",
		"Shuanghe":  "黄石市",
		"Suizhou":   "随州市",
		"Tianmen":   "荆门市",
		"Tianxing":  "咸宁市",
		"Wuhan":     "武汉市",
		"Wushan":    "武汉市",
		"Xiangyang": "襄阳市",
		"Xianning":  "咸宁市",
		"Xiaogan":   "孝感市",
		"Yichang":   "宜昌市",
		"Yicheng":   "宜昌市",
	},
	"湖南省": {
		"Changde":     "常德市",
		"Changsha":    "长沙市",
		"Chenzhou":    "郴州市",
		"Huaihua":     "怀化市",
		"Lianhua":     "郴州市",
		"Loudi":       "娄底市",
		"Pingtang":    "湘潭市",
		"Qingtan":     "湘潭市",
		"Shaoyang":    "邵阳市",
		"Xiangtan":    "湘潭市",
		"Yiyang":      "益阳市",
		"Yongzhou":    "永州市",
		"Yueyang":     "岳阳市",
		"Zhangjiajie": "张家界市",
		"Zhuzhou":     "株洲市",
	},
	"甘肃省": {
		"Baiyin":    "白银市",
		"Dingxi":    "定西市",
		"Guazhou":   "兰州市",
		"Jiayuguan": "嘉峪关市",
		"Jinchang":  "金昌市",
		"Jiuquan":   "酒泉市",
		"Lanzhou":   "兰州市",
		"Linxia":    "临夏",
		"Longnan":   "陇南市",
		"Pingliang": "平凉市",
		"Qingyang":  "庆阳市",
		"Shazhou":   "兰州市",
		"Tianshui":  "天水市",
		"Wuwei":     "武威市",
		"Zhangye":   "张掖市",
		"Zhangyelu": "张掖市",
	},
	"福建省": {
		"Fu'an":         "莆田市",
		"Fuding":        "莆田市",
		"Fuqing":        "莆田市",
		"Fuzhou":        "福州市",
		"Fu’an":         "莆田市",
		"Guankou":       "泉州市",
		"Guantou":       "泉州市",
		"Kuai’an":       "莆田市",
		"Lancheng":      "三明市",
		"Longyan":       "龙岩市",
		"Luoyang":       "龙岩市",
		"Nan'an":        "南平市",
		"Nanping":       "南平市",
		"Nanping Shequ": "南平市",
		"Ningde":        "宁德市",
		"Putian":        "莆田市",
		"Quanzhou":      "泉州市",
		"Sanming":       "三明市",
		"Sui’an":        "莆田市",
		"Xiamen":        "厦门市",
		"Yong'an":       "龙岩市",
		"Yong’an":       "龙岩市",
		"Zhangzhou":     "漳州市",
	},
	"西藏": {
		"Chéngguān Qū": "昌都市",
		"Lhasa":        "拉萨市",
		"Nagqu":        "那曲市",
		"Shannan":      "山南市",
	},
	"贵州省": {
		"Anshun":     "安顺市",
		"Bijie":      "毕节市",
		"Guiyang":    "贵阳市",
		"Liupanshui": "六盘水市",
		"Sankeshu":   "安顺市",
		"Tongren":    "铜仁市",
		"Zunyi":      "遵义市",
	},
	"辽宁省": {
		"Anshan":         "鞍山市",
		"Benxi":          "本溪市",
		"Chaoyang":       "朝阳市",
		"Chaoyanggoucun": "朝阳市",
		"Dalian":         "大连市",
		"Dalianwan":      "大连市",
		"Dandong":        "丹东市",
		"Fushun":         "抚顺市",
		"Fuxin":          "阜新市",
		"Gaizhou":        "锦州市",
		"Huludao":        "葫芦岛市",
		"Jinzhou":        "锦州市",
		"Liaoyang":       "辽阳市",
		"Liaozhong":      "辽阳市",
		"Panjin":         "盘锦市",
		"Panshan":        "鞍山市",
		"Pulandian":      "盘锦市",
		"Shenyang":       "沈阳市",
		"Tieling":        "铁岭市",
		"Yingkou":        "营口市",
	},
	"重庆市": {
		"Chongqing": "重庆市",
	},
	"陕西省": {
		"Ankang":       "安康市",
		"Baoji":        "宝鸡市",
		"Baojishi":     "宝鸡市",
		"Hancheng":     "汉中市",
		"Hanzhong":     "汉中市",
		"Jingyang":     "咸阳市",
		"Mianyang":     "咸阳市",
		"Shangluo":     "商洛市",
		"Tongchuan":    "铜川市",
		"Tongchuanshi": "铜川市",
		"Weinan":       "渭南市",
		"Xi'an":        "西安市",
		"Xianyang":     "咸阳市",
		"Xianyangshi":  "咸阳市",
		"Yan'an":       "延安市",
		"Yan’an":       "延安市",
		"Yulin":        "榆林市",
	},
	"青海省": {
		"Golog":   "果洛",
		"Haidong": "海东市",
		"Xining":  "西宁市",
		"Yushu":   "玉树",
	},
	"香港特别行政区": {
		"Wan Chai":  "湾仔区",
		"Wanchai":   "湾仔区",
		"Yuen Long": "九龙",
	},
	"黑龙江省": {
		"Daqing":       "大庆市",
		"Harbin":       "哈尔滨市",
		"Hegang":       "鹤岗市",
		"Heihe":        "黑河市",
		"Jiamusi":      "佳木斯市",
		"Jixi":         "鸡西市",
		"Mudanjiang":   "牡丹江市",
		"Qiqihar":      "齐齐哈尔市",
		"Qitaihe":      "七台河市",
		"Shuangcheng":  "双鸭山市",
		"Shuangyashan": "双鸭山市",
		"Suihua":       "绥化市",
		"Yichun":       "伊春市",
	},
}

// CityFromLatin 把拉丁字母的城市名翻译成中文，需要已归一的中文省份来消歧。
//
// 认不出时返回 false，调用方必须把城市留空，绝不能原样存入拉丁名。
func CityFromLatin(province, city string) (string, bool) {
	m, ok := cityByProvinceLatin[province]
	if !ok {
		return "", false
	}
	name, ok := m[normalizeLatinCity(city)]
	return name, ok
}

// normalizeLatinCity 剥掉两个源在城市名上附加的行政区后缀。
//
// DB-IP 会把区名写在括号里（"Guangzhou (Yuexiu Qu)"、"Haidian (Haidian Qu)"），
// 同一个城市因此有好几个写法；IP2Location 偶尔带 " City" 后缀（"Jilin City"）。
// 不剥的话每个写法都要在表里单独占一行，漏掉哪一行就是那批段查不到城市。
func normalizeLatinCity(city string) string {
	city = strings.TrimSpace(city)
	if i := strings.LastIndex(city, "("); i > 0 && strings.HasSuffix(city, ")") {
		city = strings.TrimSpace(city[:i])
	}
	return strings.TrimSuffix(city, " City")
}
